# Generated by Django 6.0.5 on 2026-05-16 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_models', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='model',
            field=models.ForeignKey(blank=True, limit_choices_to={'status__in': ['ready', 'active']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='llm_models.llmmodel'),
        ),
    ]
