# Generated by Django 6.0.5 on 2026-05-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='api_key',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='api_model_name',
            field=models.CharField(blank=True, default='gpt-4o-mini', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='api_provider',
            field=models.CharField(choices=[('local', 'Modelo local (GGUF)'), ('openai', 'OpenAI – ChatGPT')], default='local', max_length=20),
        ),
    ]
