# Generated by Django 6.0.5 on 2026-05-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('repo_id', models.CharField(max_length=300)),
                ('filename', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('size_label', models.CharField(blank=True, max_length=20)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('downloading', 'Descargando'), ('ready', 'Listo'), ('active', 'Activo'), ('error', 'Error')], default='downloading', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('local_path', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
